### ISSUE TITLE
CVE Page Redesign, Mobile Friendliness

### ISSUE THREAD

**Issue by quietcorey** [nluedtke/linux_kernel_cves#134]
**Is your feature request related to a problem? Please describe.**
In different layouts, the CVE page layout is either unusually small, or breaks the container.

**Describe the solution you'd like**
A cleaner, more consistent (with the redesign) look and feel for CVE page template.

**Comment by nluedtke** [comment]
@quietcorey is this closed with #151 ?

**Comment by quietcorey** [comment]
Yep.
