### ISSUE TITLE
Invalid JSON syntax (truncation) data/kernel_cves.json

### ISSUE THREAD

**Issue by ejhayter** [nluedtke/linux_kernel_cves#240]
**Describe the bug**
With commit a734dc99 the second half of the file is missing, leaving the JSON format invalid.

**To Reproduce**
$ jq < data/kernel_cves.json
parse error: Unfinished JSON term at EOF at line 41767, column 20

**Comment by nluedtke** [comment]
Related to a recent backend change, the JSON write failed due to a unicode character.
