### ISSUE TITLE
[BUG] Update 25Apr23 incomplete

### ISSUE THREAD

**Issue by cschmid-xse** [nluedtke/linux_kernel_cves#318]
**Describe the bug**
Database update incomplete

Updated database today via "git pull", but Update of April, 25th 2023 only contains the xxx_CVEs.txt but not the xxx_security.txt.
Please add the xxx_security.txt into the git repository.

**Comment by cschmid-xse** [comment]
Looks like only the xxx_CVE.txt was updated, database update in main folder is also incomplete

**Comment by nluedtke** [comment]
Seems like there is a git error happening toward end of the run causing the security text to not be generated. ill roll a fix.
