### ISSUE TITLE
Recent Updates

### ISSUE THREAD

**Issue by nluedtke** [nluedtke/linux_kernel_cves#33]
**Is your feature request related to a problem? Please describe.**
Its hard to tell when and what has change recently.

**Describe the solution you'd like**
Add a "Recent Update" page that essentially displays key information from the last update. This could be done in RSS format as well if desired. I see the back-end auto compiling a summary of updates and then front-end essentially just feeding that summary to the/recent_updates page.

**Describe alternatives you've considered**
The only place this information exists is the github commit section but it requires heavy parsing on the user to read.

**Comment by nluedtke** [comment]
I think the plan here should be to use the logging mechanism that is already in place. It autologs any changes it makes already. We could output that to a text file, say CHANGES.txt and have it timestamped and updated with the changing commit. @quietcorey how would we present this on the web front end? on the home page? separate page?

**Comment by quietcorey** [comment]
Could display as an info pane on the homepage if it’s only most recent, otherwise a change log page.

Markdown is a good format that we already support.

**Comment by nluedtke** [comment]
Yeah, lets plan on that. Its only going to be the most recent change. if people need something that goes further back, we have two options, they can use the git commit log. Or, we have separate running log.

**Comment by nluedtke** [comment]
This should be completed shortly. @quietcorey the most recent changes will appear in the CHANGES.md file on the tld of the repo.

**Comment by nluedtke** [comment]
This is now going to be a near term thing. The format is markdown, and autolinks to the CVE that is new or updated.

**Comment by nluedtke** [comment]
@quietcorey this is in your court now, tagging appropriately
