### ISSUE TITLE
same patches referenced two time

### ISSUE THREAD

**Issue by aliceinwire** [nluedtke/linux_kernel_cves#8]
this patches are same and referenced two times.
https://github.com/nluedtke/linux_kernel_cves/blob/a65213e292bda373f7b343f0b424d4e43d634cc4/4.9/4.9_security.txt#L129
https://github.com/nluedtke/linux_kernel_cves/blob/a65213e292bda373f7b343f0b424d4e43d634cc4/4.9/4.9_security.txt#L128

**Comment by nluedtke** [comment]
I see you closed this. But just wanted to clarify incase someone else is watching. 

That patch actually fixes both assigned issues. To double check I check Ubuntu, Debian, and RedHat database to make sure it wasn't an error. Good looking out though, Thanks for checking.

**Comment by aliceinwire** [comment]
yes, I thought of that, so I closed it. 
my only thought was to make it more computer parsable but it was less problematic than I thought.

**Comment by aliceinwire** [comment]
by the way, this repo what is used for?

**Comment by nluedtke** [comment]
We maintained a custom kernel that was based off upstream releases (not a
distro release). So we needed a way to list out the CVEs that were in each
upstream release and thus our release. This repo allowed for us to track
that using other internal tools, then allowed us to quickly test
backporting fixes from newer kernels or from distros if the fixes hadn't
made mainline.

**Comment by aliceinwire** [comment]
I'm using it for this:
https://github.com/aliceinwire/elivepatch/blob/master/elivepatch_client/client/security.py#L12
Is a security automatic live patch system for Gentoo/Upstream
