### ISSUE TITLE
[BUG] CHANGES links dont work on mobile

### ISSUE THREAD

**Issue by nluedtke** [nluedtke/linux_kernel_cves#84]
**Describe the bug**
On mobile, when I click a link on the CHANGES section it routes back to /.

**To Reproduce**
1. Click on any link in the CHANGES section.
2. Be routed back to / instead of where link should go

**Expected behavior**
The link should be followed.

**Smartphone (please complete the following information):**
 - Device: iPhone6s
 - OS: iOS 12.1.2
 - Browser: Chome

**Comment by nluedtke** [comment]
this might be caused by html5 support on iOS....can't find clear documentation on it.

**Comment by quietcorey** [comment]
@nluedtke Seems to be resolved with https://github.com/nluedtke/linux_kernel_cves/pull/109
