### ISSUE TITLE
Empty ruleset in cve.vue

### ISSUE THREAD

**Issue by nluedtke** [nluedtke/linux_kernel_cves#92]
.nvd-text is an empty ruleset which generates linting errors.
https://github.com/nluedtke/linux_kernel_cves/blob/b82a05297f8a228cc60436cffea35eeb4592b0c9/ui/src/components/cve.vue#L130-L131

**Comment by nluedtke** [comment]
@quietcorey is this rule set even needed?

**Comment by quietcorey** [comment]
apparently not
